title: Page
pages: true
files: true
fields:
  title:
    label: Title
    type:  text
    disabled: true
  defaultlenguage:
    label: Default lenguage (if one lenguage only, ignore it)
    type: select
    default: english
    options:
      english: English
      italiano: Italiano
  text:
    label: English area
    type:  textarea
  textita:
    label: Area italiana
    type:  textarea
  videoembed:
    label: Video
    type: textarea
    size: large
    help: Paste embed code into here to have video above images.
